// ES6 module syntax
import LocalizedStrings from 'react-native-localization';

let AppStrings = new LocalizedStrings({
  en: {
    BTN_SIGNUP_TXT: 'Sign Up',
    BTN_LOGIN_TXT: 'Log In',
    PASSWORD: 'Password',
    ENTER_PASSWORD: 'Enter Password',
    ENTER_EMAIL: 'Enter Email',
    ENTER_PHONE: 'Enter Phone Number',
    OTHER_SIGN_IN: 'Or sign in with',
    OTHER_SIGN_UP: 'Or sign up with',
    NOT_ACCOUNT: 'Don’t have an account?',
    SIGN_UP_HERE: ' Sign Up here',
    CONTINUE_AS_GUEST: 'Continue as guest',
    WELCOME_BACK: 'Welcome BACK!',
    ACCOUNT_SIGNI_IN: 'Sign in to your account',
    FORGOT_PASSWORD: 'Forgot Password?',
    RESET_PASSWORD: 'Reset Password',
    VOTAR: 'VOTER',
    VOTAR_DISCRIPTION: 'I want to support my favorite candidates',
    CREATE_AN_ACCOUNT: 'Create an Account',
    CHOOSE_ROLE: 'Choose a role for a customized experience',
    CANDIDATE: 'CANDIDATE',
    CANDIDATE_DISCRIPTION: 'I want to raise funds ',
    CONTINUE: 'Continue',
    EXISTING_USER: 'Existing User?',
    NOON_EXISTING_USER: 'Create an account here?',
    SIGN_UP_EMAIL_PHONE: 'Sign Up with Email or Phone',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    ZIP_CODE: 'ZIP Code',
    NEXT: 'Next',
    PROVIDE_DETAILS: 'Please provide the following details',
    TELL_US_BIT_YOURSELF: 'Tell us a bit about yourself',
    WHERE_DO_YOU_WORK: 'Where do you work?',
    COMPAIN_FINACE:
      'Campaign finance law requires us to collect your employment information. In order to stay compliant withXXXXX, you will need to update your employer info here if it changes.',
    OCCUPATION: 'Occupation',
    EMPLOYER: 'Employer',
    ENTTER_CREDENTIAL: 'Please enter your credentials',
    EMAIL_ADDRESS: 'Email Address',
    PHONE_NUMBER: 'Phone Number',
    CREATE_PASSWORD: 'Create Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    CREATE_NEW_PASSWORD: 'Create New Password',
    CONFIRM_NEW_PASSWORD: 'Confirm New Password',
    BY_SIGN_UP: 'By signing up, you agree to our',
    TERMS_AND_CONDITION: ' Terms & Conditions',
    VERIFICATION: 'Verification',
    PLEASE_CHOOSE_VERIFICATION: 'Please choose verification method',
    PHONE: 'Phone',
    EMAIL: 'Email',
    VERIFY: 'verify',
    VERIFIED: 'verified!',
    WE_HAVE_SEND_CODE: 'We have sent a verification code on \n registered ',
    ENTER_VERIFICATION_CODE: 'Enter the verification code sent to ',
    RESEND_CODE: 'Resend Verification Code',
    RESEND_CODE_AGAIN: 'Resend Verification Code in ',
    SUBMIT: 'Submit',
    UPDATE_ENTERED_PHONE_NUMBER: 'Update Entered ',
    UPDATE_PHONE_NUMBER: 'Update Phone Number',
    UPDATE_EMAIL: 'Update Email',
    CANCEL: 'Cancel',
    UPDATE: 'Update ',
    SKIP: 'Skip',
    DONE: 'Done',
    WELCOME_TO_VOTR: 'welcome to votr!',
    LOGOUT: 'Logout',
    FIRST_NAME_CONTAINS_NUMBER: 'First name should not contain a number',
    LAST_NAME_CONTAINS_NUMBER: 'Last name should not contain a number',
    REGISTERED_PHONE: 'Please enter your registered phone number',
    VERIFICATION_CODE_SENT_RESET:
      'Verification code sent on your registered phone number to reset the password',
    SEND_CODE: 'Send Verification Code',
    FIRST_NAME_CONTAINS_SYMBOL: 'First name should not contain a symbol',
    LAST_NAME_CONTAINS_SYMBOL: 'Last name should not contain a symbol',

    FIRST_NAME_CONTAINS_SYMBOL_NUMBER:
      'First name should not contain a symbol or number',
    LAST_NAME_CONTAINS_SYMBOL_NUMBER:
      'Last name should not contain a symbol or number',

    ZIP_CODE_LIMIT_NUMBER: 'Zip code must be 5 characters long',

    ZIP_CODE_LIMIT_NUMBER: 'Zip code must be 5 characters long',
    ZIP_CODE_CONTAINS_SYMBOL_NUMBER: 'Zip should not contain a symbol',
    EMPLOYER_CONTAINS_NUMBER: 'Employer should not contain a number',
    OCCUPATION_NAME_CONTAINS_NUMBER: 'Occupation should not contain a number',
    EMPLOYER_CONTAINS_SYMBOL: 'Employer should not contain a special symbol',
    OCCUPATION_NAME_CONTAINS_SYMBOL:
      'Occupation should not contain a special symbol',
    SAVE_PASSWORD: 'Save Password',
    VALID_EMAIL: 'Please enter a valid email',
    EMPTY_EMAIL: "Email can't be empty",
    EMPTY_PHONE: "Phone number can't be empty",
    VALID_PHONE: 'Please enter a valid phone number',
    VALID_PHONE_LENGTH: 'Phone number must be between 8-15 character',
    PASSWORD_SAME: 'Entered passwords do not match',
    PASSWORD_8_CHARACTER: 'Password must be 8 characters long.',
    PASSWORD_16_CHARACTER: 'Password length should be 16 characters maximum.',
    PASSWORD_NUMBER: 'Password must contain atleast a number.',
    PASSWORD_CHARACTER: 'Password must contain atleast a character',
    PASSWORD_LOWER_CHARACTER:
      'Password must contain atleast one lowercase character',
    PASSWORD_UPPER_CHARACTER:
      'Password must contain atleast one uppercase character',
    PASSWORD_SPECIAL_SYMBOL: 'Password must contain atleast one special symbol',

    PLEASE_SELECT_VERIFICATION_OPTION: 'Please select any one option',
    INCORRECT_RECOVERY_CODE: ' Incorrect recovery code',
    EMPTY_RECOVERY_CODE: ' Empty recovery code',
    VERIFICATION_CODE_SENT: 'Verification code sent!',

    OFFLINE: 'Please check your internet connection',
    ENTER_EMAIL_TOKEN: 'Enter token here',
    ADD_PROFILE_PHOTO: 'Add Profile Photo',
    Choose_from_Library: 'Choose from Library',
    Take_Photo: 'Take Photo',
    //Address
    PLEASE_ENTER_YOUR_ADDRESS: 'Please enter your address',
    ADDRESS: 'Address',
    CITY: 'City',
    STATE: 'State',
    LEVEL: 'Level',
    PARTY: 'Party',
    OFFICE_SOUGHT: 'Office Sought',
    COMMITTEE_NUMBER: 'Committee Number',
    PRIMARY_DATE: 'Primary Date',
    ELECTION_DATE: 'Election Date',
    SPECIAL_ELECTION: 'This is a special election:',
    SELECT_LEVEL: 'Select Level',
    SELECT_PARTY: 'Select Party',

    //LEVELS
    FEDERAL: 'Federal',
    LOCAL: 'Local',
    REPUBLICAN: 'Republican',
    DEMOCRAT: 'Democrat',
    LIBERTARIAN: 'Libertarian',
    INDEPENDENT: 'Independent',
    SHARE_YOUR_KEY: 'Share your key issues to highlight',
    ADD_KEY_ISSUE: 'Add Key Issue',
    ENTER_DISCRIPTION: 'Enter description...',
    LINK_TWITTER: 'Link Your Twitter Account',
    ADD_CAMPAIGN_EVENTS: 'Add Campaign Events',
    CAMPAIGN_EVENTS: 'Campaign Events',
    ENTER_USERNAME: 'Enter Username',
    ADD_CAMPAIGN_MODAL: 'Add Campaign Event',
    TITLE: 'Title',
    DATE: 'Date',
    TIME: 'Time',
    LOCATION: 'Location',
    YES: 'Yes',
    NO: 'No',
    VALID_COMM_NUMBER: 'Please enter a valid committee number',
    COMM_NUMBER_SYMBOL: 'Committee number should not contain a symbol',
    //Survey
    GETTING_STARTED_SYRVEY: 'Getting started',
    GETTING_STARTED_HEADING:
      'Help us to know your preferences to optimize your experience ',
    GET_STARTED: 'Get Started',
    YOU_CAN_ALWAYS_EDIT_RESPONSE: 'You can always edit your responses later.',
    WE_RECOMMED_THAT_YOU_ANSWER:
      'We recommend that you answer as many questions as possible to help us understand your preference. ',
    PLEASE_SELECT_ANSWER: 'Please select an answer',
    MY_CANDIDATE: 'My Candidates',
    SEARCH: 'Search Candidates',
    HII: 'Hi',
    VIEW_ALL: 'View All',
    //GUEST
    HI_THERE: 'Hi there!',
    GUEST_SIGNUP: 'Please sign up to view  recommendations',
    TRENDING: 'Trending Candidates',
    //VOTER HOME
    VIEW_PROFILE: 'View Profile',
    //Candidate DetailsScreen
    swipeIntro: 'Swipe Left & Right',
    runningFor: 'Running for: ',
    primaryDate: 'Primary Date: ',
    electionDate: 'Election Date: ',
    raised: 'Raised',
    followers: 'Followers',
    editProfile: 'Edit Profile',
    latestTweets: 'Latest Tweeets',
    keyIssues: 'Key Issues',
    campaignEvents: 'Campaign Events',
    viewOnTwitter: 'View On Twitter',
    SureLogout: 'Are you sure you want to log out?',
    Search: 'Search',
    Following: 'Following',
    Donate: 'Donate',
    Follow: 'Follow',
    Unfollow: 'Unfollow',
    DonationLimitExcedText1:
      'You have reached maximum donation limit for this candidate.',
    DonationLimitExcedText2:
      'You will be eligible to donate again in next election.',
    DonationNotCompletedText1:
      'Candidate is not eligible to receive donation yet.',
    DonationNotCompletedText2: 'We’ll notify you once it’s done.',
    Okay: 'Okay',
    enterAccount: 'Make a secure donation to',
    continueToPay: 'Continue To Pay',
    enterAmount: 'Enter amount',
    account: 'Account',
    completeProfile: 'Complete Profile',
    completeProfileText:
      'Verify your email to optimize your experience and receive the latest updates',
    verifyEmail: 'Verfiy Email',
    verifyPhone: 'Verfiy Phone',
    cancel: 'Cancel',
    AMOUNT: 'Amount',
    match: '% Match',



    yearly :"Yearly",
    monthly: "Monthly",
  },
});

export default AppStrings;
